### PR TITLE
Running in parallel

### PR DESCRIPTION
**Pull request by Chemaclass**
## 📚 Description

Closes: https://github.com/TypedDevs/bashunit/issues/354

## 🔖 Changes

- Add parallel running: `-p|--parallel`
- Add possibility of disabling parallel execution with `--no-parallel`

## ✅ To-do list

- [x] I updated the `CHANGELOG.md` to reflect the new feature or fix
- [x] I updated the documentation to reflect the changes

### Running the entire test suite sync (~43s)

Screenshot 2024-10-10 at 01 12 16

### Running the entire test suite in parallel (~15s) - 65.12% improment! 🚀 

Screenshot 2024-10-10 at 01 39 12

### Running parallel tests verbose

Screenshot 2024-10-10 at 01 55 41

### Documentation

Screenshot 2024-10-10 at 00 34 07

### CODE REVIEW

**Review by CosmeValera — APPROVED** [review]
Good job as always !!!

**Review by khru — APPROVED** [review]

**Review by khru — COMMENTED** [review]
I would just say that for me parallel testing should always be the default way to run, as it is not just for performance, but also to know that your tests do not depend on each other,

I would rather suggest that it be always active by default in subsequent versions and that it can be disabled. 

That's my opinion, I think that the value that active brings is always greater, and that only in case you need to disable it because your code needs it, you do it. 


This opens up other issues such as being able to prevent a test file from being launched in parallel, this is common in other testing frameworks.

**Comment by khru** [comment]
The tests are not good in alpine

**Comment by Chemaclass** [comment]
I would rather not keep the parallel testing as default behavior but as it was until now. 
This is the default behavior on PHPUnit, Pest, JUnit, among others. However I found that Jest run them in parallel "when it make sense" based on some heuristic -size of tests, number of tests, etc... but I find this too complicated to get into this right now. 

Aiming for simplicity, I am in favor of:
If you want parallel tests you can enable with `-p|--parallel` or in your .env `BASHUNIT_PARALLEL_RUN=true`

**Pull request merged**
